apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-k8s-config
data:
  application.properties: |
    spring.application.name=spring-boot-k8s
    server.port=8080
    
    # Actuator configuration
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.show-details=always
    
    # Datadog configuration
    dd.service.name=spring-boot-k8s
    dd.env=production
    dd.version=1.0.0
