apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s
  labels:
    app: spring-boot-k8s
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot-k8s
